name: Java CI

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up JDK 21
        uses: actions/setup-java@v3  # Updated to the latest version
        with:
          java-version: '21'
          distribution: 'temurin'  # Specify Java distribution (AdoptOpenJDK/Temurin)

      - name: Build with Maven
        run: mvn clean install  # Step to build the project with Maven

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: maven-build
          path: target/*.jar  # Path to the JAR file in the target/ folder
