name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21 (not 11)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Use JDK 21 for your Maven build

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install  # Use Maven to build the project

      # Step 4: Upload the built JAR file as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: maven-build
          path: target/*.jar  # Upload JAR from Maven's target/ directory
