name: Java CI

on:
  push:
    branches:
      - master  # Triggers on push to the main branch
  pull_request:
    branches:
      - master  # Triggers on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
