name: Java CI

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the build environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest version of actions

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Updated to v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Specify Java distribution (AdoptOpenJDK/Temurin)

      - name: Build with Maven (with Debugging)
        run: mvn clean install -X  # Enable Maven's debug output (-X)

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Use the latest version
        with:
          name: maven-build
          path: target/*.jar  # Path to the JAR file in the target/ folder
